require 'rails_helper'
require 'capybara/rails'
# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/api/v1/questions", type: :feature do
  describe "GET /" do
    before :each do 
      User.create(id:1, email: 'marcelomaidden@gmail.com', password: '123456')
      Question.create(user_id: 1, 
        title: 'Can I have a help on how to use EmberJS?',
        description: 'I am facing problems understanding EmberJS'
      )
    end
    it "renders a successful response" do
      visit '/api/v1/questions'
      expect(page).to have_content 'Can I have a help on how to use EmberJS?'
    end
  end

  describe "Tries to create question without credentials" do
    it 'returns unauthorized response' do
      session = ActionDispatch::Integration::Session.new(Rails.application)
      response = session.post("/api/v1/questions")
      expect(response).to eq(401)
    end
  end
end
